
exports.up = function(knex) {
  return knex.raw(`
    CREATE TABLE practice.person(
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );
  `);
};

exports.down = function(knex) {
  return knex.raw('DROP TABLE practice.person');
};
