exports.up = function (knex) {
    return knex.raw(`
      CREATE TABLE practice.response(
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          score INTEGER NOT NULL CHECK(score >= 0 AND score <=3),
          review_after TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
          spacing INTEGER NOT NULL CHECK(spacing >= 0) DEFAULT 0,
          ease_factor NUMERIC(7, 4) NOT NULL CHECK(ease_factor >= 1.3) DEFAULT 2.5,
          card_id INTEGER REFERENCES practice.response(id),
          person_id INTEGER REFERENCES practice.person(id),
          created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
      );
  
      CREATE INDEX response_id_idx ON practice.response(card_id);
      CREATE INDEX response_person_id_idx ON practice.response(person_id);
  
      COMMENT ON TABLE practice.response IS '@omit create,update, delete
      An individual graded response to a flash card';
      COMMENT ON COLUMN practice.response.id IS 'The primary unique identifier for a flash card response';
      COMMENT ON COLUMN practice.response.score IS 'A value indicating how well the answer was remembered. Ranges from 0 to 3.';
      COMMENT ON COLUMN practice.response.review_after IS 'The calculated next time the card should be reviewed';
      COMMENT ON COLUMN practice.response.spacing IS 'The number of days until review';
      COMMENT ON COLUMN practice.response.ease_factor IS 'A factor indicating how easy or hard the card is';
      COMMENT ON COLUMN practice.response.card_id IS 'The card that the response is for';
      COMMENT ON COLUMN practice.response.person_id IS 'The user who made the response';
      COMMENT ON COLUMN practice.response.created_at IS 'The time the response was made';
    `);
  };
  
  exports.down = function (knex) {
    return knex.raw(`DROP TABLE practice.response`);
  };
  